version: 2.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.2-stretch-node
    resource_class: xlarge
    steps:
      - checkout
      - run: echo "test step"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
