version: 2.0
jobs:
#  build:
#    docker:
#      - image: circleci/ruby:2.4.2-stretch-node
#    resource_class: xlarge
#    steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run: "echo 'build'"
  build:
    docker:
      - image: circleci/ruby:2.4.2-stretch-node
    resource_class: medium
    steps:
      - checkout
      - run: "echo 'build'"
#  deploy:
#    docker:
#      - image: circleci/ruby:2.4.2-stretch-node
#    resource_class: xlarge
#    steps:
#      - checkout
#      - run: "echo 'deploy'"

#workflows:
#  version: 2
#  test_and_deploy:
#    jobs:
#      - test_1:
#          requires:
#            - test
#      - test_2:
#          requires:
#            - test
#      - deploy:
#          requires:
#            - test_1
#            - test_2
#
