version: 2.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.2-stretch-node
    resource_class: xlarge
    steps:
      - checkout
      - run: echo "test step"
  deploy:
    docker:
      - image: circleci/ruby:2.4.2-stretch-node
    resource_class: medium
    steps:
      - checkout
      - run: echo "deploy step"
  print:
    docker:
      - image: circleci/ruby:2.4.2-stretch-node
    resource_class: medium
    steps:
      - checkout
      - run: echo "print step"

workflows:
  version: 2
  test_and_deploy_and_print:
    jobs:
      - test
      - deploy
      - print
